[package]
name = "foundation"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", default-features = false, features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { version = "0.7", default-features = false, features = ["io"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "ansi"] }
axum = { version = "0.6", default-features = false, features = ["tokio", "http1", "json"] }
serde = { version = "1.0", default-features = false, features = ["derive", "rc"] }
tower-http = { version = "0.4", default-features = false, features = ["cors", "fs"] }
time = { version = "0.3", default-features = false, features = ["serde", "formatting"] }
serde_yaml = { version = "0.9", default-features = false }
clap = { version = "4.3", features = ["derive", "env"] }
markdown = "1.0.0-alpha.9"
tracing = "0.1"
anyhow = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = true

# by overriding our dependencies' compilation settings, we can further optimize>
# https://docs.rust-embedded.org/book/unsorted/speed-vs-size.html#optimizing-de>
[profile.release.package."*"]
codegen-units = 1
